services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
